import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, isValidObjectId } from 'mongoose';
import { Page, PageDocument } from '@rent-ghar/db/schemas/page.schema';
import { CreatePageDto } from '@rent-ghar/dtos/page/createpage.dto';
import { UpdatePageDto } from '@rent-ghar/dtos/page/updatepage.dto';

// Helper function to generate slug from text
function generateSlug(text: string): string {
    return text
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') || `page-${Date.now()}`;
}

import { IndexNowService } from '../indexnow/indexnow.service';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class PageService {
    constructor(
        @InjectModel(Page.name) private readonly pageModel: Model<PageDocument>,
        private indexNowService: IndexNowService,
        private configService: ConfigService,
    ) {}

    async create(createPageDto: CreatePageDto): Promise<PageDocument> {
        try {
            // Validate required fields
            if (!createPageDto.title || !createPageDto.title.trim()) {
                throw new BadRequestException('Title is required');
            }
            if (!createPageDto.content || !createPageDto.content.trim()) {
                throw new BadRequestException('Content is required');
            }

            const pageData: any = {
                title: createPageDto.title.trim(),
                content: createPageDto.content.trim(),
                excerpt: createPageDto.excerpt?.trim() || undefined,
                status: createPageDto.status || 'DRAFT',
                metaTitle: createPageDto.metaTitle?.trim() || undefined,
                metaDescription: createPageDto.metaDescription?.trim() || undefined,
                canonicalUrl: createPageDto.canonicalUrl?.trim() || undefined,
                featuredImage: createPageDto.featuredImage?.trim() || undefined,
                keywords: createPageDto.keywords || [],
            };

            // Handle slug - if not provided, it will be auto-generated by schema pre-save hook
            if (createPageDto.slug && createPageDto.slug.trim()) {
                pageData.slug = createPageDto.slug.trim().toLowerCase();
            }

            const page = new this.pageModel(pageData);
            
            // Try to save, handle duplicate slug by appending a number
            try {
                const savedPage = await page.save();
                
                if (savedPage.status === 'PUBLISHED' && savedPage.slug) {
                    const host = this.configService.get<string>('APP_HOST') || 'propertydealer.pk';
                    const url = `https://${host}/${savedPage.slug}`;
                    this.indexNowService.submitUrl(url).catch(err => {
                        console.error('Failed to submit URL to IndexNow:', err);
                    });
                }

                return savedPage;
            } catch (saveError: any) {
                // If duplicate slug error, try to generate a unique one
                if (saveError.code === 11000 && saveError.keyPattern?.slug) {
                    let baseSlug = pageData.slug || generateSlug(createPageDto.title.trim());
                    if (!baseSlug) {
                        baseSlug = generateSlug(createPageDto.title);
                    }
                    
                    // Try to find a unique slug by appending numbers
                    let uniqueSlug = baseSlug;
                    let counter = 1;
                    let exists = true;
                    
                    while (exists && counter < 100) {
                        const existing = await this.pageModel.findOne({ slug: uniqueSlug }).exec();
                        if (!existing) {
                            exists = false;
                        } else {
                            uniqueSlug = `${baseSlug}-${counter}`;
                            counter++;
                        }
                    }
                    
                    pageData.slug = uniqueSlug;
                    const retryPage = new this.pageModel(pageData);
                    return await retryPage.save();
                }
                throw saveError;
            }
        } catch (error: any) {
            // Handle duplicate slug error
            if (error.code === 11000) {
                const duplicateField = Object.keys(error.keyPattern || {})[0];
                throw new BadRequestException(
                    `A page with this ${duplicateField} already exists. Please use a different ${duplicateField === 'slug' ? 'title' : duplicateField}.`
                );
            }
            // Re-throw validation errors
            if (error.name === 'ValidationError') {
                const messages = Object.values(error.errors || {}).map((err: any) => err.message);
                throw new BadRequestException(messages.join(', '));
            }
            // Re-throw BadRequestException
            if (error instanceof BadRequestException) {
                throw error;
            }
            // Log and re-throw other errors
            console.error('Error creating page:', error);
            throw new BadRequestException(error.message || 'Failed to create page');
        }
    }

    async getAll(): Promise<PageDocument[]> {
        return this.pageModel.find().sort({ createdAt: -1 }).exec();
    }

    async getPublished(): Promise<PageDocument[]> {
        return this.pageModel.find({ status: "PUBLISHED" }).sort({ createdAt: -1 }).exec();
    }

    async getById(id: string): Promise<PageDocument | null> {
        if (!isValidObjectId(id)) {
            throw new BadRequestException('Invalid page ID');
        }
        return this.pageModel.findById(id).exec();
    }

    async getBySlug(slug: string): Promise<PageDocument | null> {
        if (!slug || !slug.trim()) {
            throw new BadRequestException('Slug is required');
        }
        return this.pageModel.findOne({ slug: slug.trim().toLowerCase(), status: 'PUBLISHED' }).exec();
    }

    async update(id: string, updatePageDto: UpdatePageDto): Promise<PageDocument> {
        if (!isValidObjectId(id)) {
            throw new BadRequestException('Invalid page ID');
        }

        const updateData: any = {};
        
        if (updatePageDto.title) updateData.title = updatePageDto.title.trim();
        if (updatePageDto.content) updateData.content = updatePageDto.content.trim();
        if (updatePageDto.excerpt !== undefined) updateData.excerpt = updatePageDto.excerpt?.trim() || undefined;
        if (updatePageDto.status) updateData.status = updatePageDto.status;
        if (updatePageDto.metaTitle !== undefined) updateData.metaTitle = updatePageDto.metaTitle?.trim() || undefined;
        if (updatePageDto.metaDescription !== undefined) updateData.metaDescription = updatePageDto.metaDescription?.trim() || undefined;
        if (updatePageDto.canonicalUrl !== undefined) updateData.canonicalUrl = updatePageDto.canonicalUrl?.trim() || undefined;
        if (updatePageDto.featuredImage !== undefined) updateData.featuredImage = updatePageDto.featuredImage?.trim() || undefined;
        if (updatePageDto.keywords !== undefined) updateData.keywords = updatePageDto.keywords;

        // Handle slug - if provided, update it; otherwise it will be auto-generated from title
        if (updatePageDto.slug && updatePageDto.slug.trim()) {
            updateData.slug = updatePageDto.slug.trim().toLowerCase();
        }

        const page = await this.pageModel.findByIdAndUpdate(id, updateData, { new: true }).exec();
        if (!page) {
            throw new NotFoundException(`Page with ID ${id} not found`);
        }

        if (page.status === 'PUBLISHED' && page.slug) {
            const host = this.configService.get<string>('APP_HOST') || 'propertydealer.pk';
            const url = `https://${host}/${page.slug}`;
            this.indexNowService.submitUrl(url).catch(err => {
                console.error('Failed to submit URL to IndexNow:', err);
            });
        }

        return page;
    }

    async delete(id: string): Promise<PageDocument> {
        if (!isValidObjectId(id)) {
            throw new BadRequestException('Invalid page ID');
        }
        const page = await this.pageModel.findByIdAndDelete(id).exec();
        if (!page) {
            throw new NotFoundException(`Page with ID ${id} not found`);
        }
        return page;
    }
}